"""Pilot core persistence schema.

Revision ID: 0001_pilot_core
Revises:
Create Date: 2026-07-28 17:07:29.531423
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_pilot_core"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_artifacts",
        sa.Column("artifact_id", sa.String(length=255), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("analytic", sa.String(length=128), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=2048), nullable=True),
        sa.Column("commercial_rights", sa.JSON(), nullable=True),
        sa.Column("class_list", sa.JSON(), nullable=False),
        sa.Column("preprocessing", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sha256 IS NULL OR length(sha256) = 64", name="ck_model_artifacts_sha256"
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    op.create_table(
        "sites",
        sa.Column("site_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timezone_name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("site_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=1024), nullable=False),
        sa.Column("totp_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('viewer', 'operator', 'admin')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_entries",
        sa.Column("audit_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=128), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.user_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("audit_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("audit_entries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_entries_entity", ["entity_type", "entity_id", "occurred_at"], unique=False
        )

    op.create_table(
        "cameras",
        sa.Column("camera_id", sa.String(length=128), nullable=False),
        sa.Column("site_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_reference", sa.String(length=1024), nullable=False),
        sa.Column("codec", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("codec IN ('h264', 'h265')", name="ck_cameras_codec"),
        sa.CheckConstraint(
            "state IN ('starting', 'online', 'degraded', 'offline', 'reconnecting')",
            name="ck_cameras_state",
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.site_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("camera_id"),
        sa.UniqueConstraint("site_id", "name", name="uq_cameras_site_name"),
    )
    with op.batch_alter_table("cameras", schema=None) as batch_op:
        batch_op.create_index("ix_cameras_site_state", ["site_id", "state"], unique=False)

    op.create_table(
        "gate_reports",
        sa.Column("report_id", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("artifact_id", sa.String(length=255), nullable=False),
        sa.Column("report_type", sa.String(length=32), nullable=False),
        sa.Column("site_id", sa.String(length=128), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("report_reference", sa.String(length=2048), nullable=False),
        sa.Column("report_sha256", sa.String(length=64), nullable=False),
        sa.Column("signed_by", sa.String(length=255), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stream_count", sa.Integer(), nullable=True),
        sa.Column("result_mode", sa.String(length=16), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "report_type IN ('target_site', 'capacity', 'shadow_stage')",
            name="ck_gate_reports_type",
        ),
        sa.CheckConstraint(
            "result_mode IN ('disabled', 'shadow', 'operator')", name="ck_gate_reports_result_mode"
        ),
        sa.CheckConstraint("length(report_sha256) = 64", name="ck_gate_reports_sha256"),
        sa.CheckConstraint(
            "stream_count IS NULL OR stream_count >= 1", name="ck_gate_reports_stream_count"
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["model_artifacts.artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.site_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("report_id"),
        sa.UniqueConstraint(
            "artifact_id", "report_type", "report_reference", name="uq_gate_reports_provenance"
        ),
    )
    op.create_table(
        "camera_health_samples",
        sa.Column("health_sample_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("camera_id", sa.String(length=128), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("last_frame_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconnect_count", sa.Integer(), nullable=False),
        sa.Column("dropped_samples", sa.Integer(), nullable=False),
        sa.Column("degraded_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('starting', 'online', 'degraded', 'offline', 'reconnecting')",
            name="ck_camera_health_state",
        ),
        sa.CheckConstraint("dropped_samples >= 0", name="ck_camera_health_dropped_samples"),
        sa.CheckConstraint("reconnect_count >= 0", name="ck_camera_health_reconnect_count"),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.camera_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("health_sample_id"),
    )
    with op.batch_alter_table("camera_health_samples", schema=None) as batch_op:
        batch_op.create_index(
            "ix_camera_health_camera_observed", ["camera_id", "observed_at"], unique=False
        )

    op.create_table(
        "candidate_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=1024), nullable=False),
        sa.Column("camera_id", sa.String(length=128), nullable=False),
        sa.Column("module", sa.String(length=128), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("peak_confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("model_artifact_id", sa.String(length=255), nullable=False),
        sa.Column("gate_mode", sa.String(length=16), nullable=False),
        sa.Column("evidence_status", sa.String(length=16), nullable=False),
        sa.Column("review_status", sa.String(length=16), nullable=False),
        sa.Column("transition_history", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "evidence_status IN ('pending', 'ready', 'failed', 'unavailable')",
            name="ck_candidate_events_evidence_status",
        ),
        sa.CheckConstraint(
            "gate_mode IN ('disabled', 'shadow', 'operator')", name="ck_candidate_events_gate_mode"
        ),
        sa.CheckConstraint(
            "review_status IN ('observation', 'candidate', 'confirmed', 'rejected', 'expired', 'escalated')",
            name="ck_candidate_events_review_status",
        ),
        sa.CheckConstraint(
            "schema_version = 'candidate-event.v1'", name="ck_candidate_events_schema"
        ),
        sa.CheckConstraint("last_seen_at >= opened_at", name="ck_candidate_events_time_range"),
        sa.CheckConstraint(
            "(review_status = 'observation' AND transition_history = 'observation') OR "
            "(review_status = 'candidate' AND "
            "transition_history = 'observation>candidate') OR "
            "(review_status = 'confirmed' AND "
            "transition_history = 'observation>candidate>confirmed') OR "
            "(review_status = 'rejected' AND "
            "transition_history = 'observation>candidate>rejected') OR "
            "(review_status = 'expired' AND "
            "transition_history = 'observation>candidate>expired') OR "
            "(review_status = 'escalated' AND "
            "transition_history = 'observation>candidate>confirmed>escalated')",
            name="ck_candidate_events_lifecycle",
        ),
        sa.CheckConstraint(
            "peak_confidence >= 0 AND peak_confidence <= 1",
            name="ck_candidate_events_peak_confidence",
        ),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.camera_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["model_artifact_id"], ["model_artifacts.artifact_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    with op.batch_alter_table("candidate_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_candidate_events_camera_opened", ["camera_id", "opened_at"], unique=False
        )
        batch_op.create_index(
            "ix_candidate_events_filters",
            ["module", "gate_mode", "review_status", "opened_at"],
            unique=False,
        )

    op.create_table(
        "observations",
        sa.Column("observation_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=1024), nullable=False),
        sa.Column("camera_id", sa.String(length=128), nullable=False),
        sa.Column("stream_epoch", sa.String(length=36), nullable=False),
        sa.Column("source_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timestamp_quality", sa.String(length=32), nullable=False),
        sa.Column("monotonic_seq", sa.Integer(), nullable=False),
        sa.Column("module", sa.String(length=128), nullable=False),
        sa.Column("class_name", sa.String(length=128), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("bbox", sa.JSON(), nullable=False),
        sa.Column("track_id", sa.String(length=255), nullable=True),
        sa.Column("model_artifact_id", sa.String(length=255), nullable=False),
        sa.Column("sample_kind", sa.String(length=32), nullable=False),
        sa.Column("runtime_state", sa.String(length=32), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "runtime_state IN ('starting', 'online', 'degraded', 'offline', 'reconnecting')",
            name="ck_observations_runtime_state",
        ),
        sa.CheckConstraint(
            "sample_kind IN ('fresh', 'cached_display')", name="ck_observations_sample_kind"
        ),
        sa.CheckConstraint("schema_version = 'observation.v1'", name="ck_observations_schema"),
        sa.CheckConstraint(
            "timestamp_quality IN ('camera_rtcp', 'host_ntp_fallback')",
            name="ck_observations_timestamp_quality",
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_observations_confidence"
        ),
        sa.CheckConstraint("monotonic_seq >= 0", name="ck_observations_monotonic_seq"),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.camera_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["model_artifact_id"], ["model_artifacts.artifact_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("observation_id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_observations_camera_source_time", ["camera_id", "source_time"], unique=False
        )

    op.create_table(
        "evidence",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("object_key", sa.String(length=2048), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("codec", sa.String(length=8), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_reference", sa.String(length=2048), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("codec IN ('h264', 'h265')", name="ck_evidence_codec"),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'failed', 'unavailable')", name="ck_evidence_status"
        ),
        sa.CheckConstraint("end_at >= start_at", name="ck_evidence_time_range"),
        sa.CheckConstraint("length(sha256) = 64", name="ck_evidence_sha256"),
        sa.ForeignKeyConstraint(["event_id"], ["candidate_events.event_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evidence_id"),
        sa.UniqueConstraint("event_id", "object_key", name="uq_evidence_event_object"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_table(
        "notification_outbox",
        sa.Column("outbox_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'delivering', 'delivered', 'dead_letter')",
            name="ck_notification_outbox_status",
        ),
        sa.ForeignKeyConstraint(["event_id"], ["candidate_events.event_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("outbox_id"),
        sa.UniqueConstraint("event_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "reviews",
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=False),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "from_status IN ('candidate', 'confirmed')", name="ck_reviews_from_status"
        ),
        sa.CheckConstraint(
            "to_status IN ('confirmed', 'rejected', 'expired', 'escalated')",
            name="ck_reviews_to_status",
        ),
        sa.CheckConstraint(
            "(from_status = 'candidate' AND "
            "to_status IN ('confirmed', 'rejected', 'expired')) OR "
            "(from_status = 'confirmed' AND to_status = 'escalated')",
            name="ck_reviews_legal_transition",
        ),
        sa.ForeignKeyConstraint(["event_id"], ["candidate_events.event_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.user_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("event_id", "idempotency_key", name="uq_reviews_event_idempotency"),
    )
    op.create_table(
        "delivery_attempts",
        sa.Column("delivery_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("outbox_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("response_reference", sa.String(length=2048), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('sending', 'delivered', 'failed')", name="ck_delivery_attempts_status"
        ),
        sa.CheckConstraint("attempt_number >= 1", name="ck_delivery_attempts_number"),
        sa.ForeignKeyConstraint(
            ["outbox_id"], ["notification_outbox.outbox_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("delivery_attempt_id"),
        sa.UniqueConstraint("outbox_id", "attempt_number", name="uq_delivery_attempt_number"),
    )
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        op.execute(
            """
            CREATE TRIGGER trg_audit_entries_no_update
            BEFORE UPDATE ON audit_entries
            BEGIN
                SELECT RAISE(ABORT, 'audit entries are append-only');
            END
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_audit_entries_no_delete
            BEFORE DELETE ON audit_entries
            BEGIN
                SELECT RAISE(ABORT, 'audit entries are append-only');
            END
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_notification_outbox_confirmed_operator
            BEFORE INSERT ON notification_outbox
            FOR EACH ROW
            BEGIN
                SELECT CASE
                    WHEN NOT EXISTS (
                        SELECT 1
                        FROM candidate_events
                        WHERE event_id = NEW.event_id
                          AND gate_mode = 'operator'
                          AND review_status = 'confirmed'
                    )
                    THEN RAISE(
                        ABORT,
                        'notification outbox requires a confirmed operator event'
                    )
                END;
                SELECT CASE
                    WHEN NOT EXISTS (
                        SELECT 1
                        FROM candidate_events AS event
                        JOIN reviews AS review
                          ON review.event_id = event.event_id
                         AND review.from_status = 'candidate'
                         AND review.to_status = 'confirmed'
                        WHERE event.event_id = NEW.event_id
                          AND event.transition_history = 'observation>candidate>confirmed'
                    )
                    THEN RAISE(
                        ABORT,
                        'notification outbox requires valid review provenance'
                    )
                END;
            END
            """
        )
        for evidence_operation in ("INSERT", "UPDATE"):
            op.execute(
                f"""
                CREATE TRIGGER trg_evidence_duration_{evidence_operation.lower()}
                BEFORE {evidence_operation} ON evidence
                FOR EACH ROW
                WHEN NEW.end_at <= NEW.start_at
                  OR (
                      julianday(NEW.end_at) - julianday(NEW.start_at)
                  ) * 86400.0 > 10.0001
                  OR (
                      NEW.status = 'ready'
                      AND (
                          julianday(NEW.end_at) - julianday(NEW.start_at)
                      ) * 86400.0 < 3.9999
                  )
                BEGIN
                    SELECT RAISE(
                        ABORT,
                        'evidence duration violates the bounded clip policy'
                    );
                END
                """
            )
    elif dialect == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION pilot_reject_audit_mutation()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'audit entries are append-only';
            END;
            $$
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_audit_entries_append_only
            BEFORE UPDATE OR DELETE ON audit_entries
            FOR EACH ROW EXECUTE FUNCTION pilot_reject_audit_mutation()
            """
        )
        op.execute(
            """
            CREATE OR REPLACE FUNCTION pilot_validate_notification_outbox()
            RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE
                event_gate_mode text;
                event_review_status text;
                event_transition_history text;
            BEGIN
                SELECT gate_mode, review_status, transition_history
                INTO event_gate_mode, event_review_status, event_transition_history
                FROM candidate_events
                WHERE event_id = NEW.event_id;
                IF event_gate_mode IS DISTINCT FROM 'operator'
                   OR event_review_status IS DISTINCT FROM 'confirmed' THEN
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'notification outbox requires a confirmed operator event';
                END IF;
                IF event_transition_history <> 'observation>candidate>confirmed'
                   OR NOT EXISTS (
                       SELECT 1
                       FROM reviews
                       WHERE event_id = NEW.event_id
                         AND from_status = 'candidate'
                         AND to_status = 'confirmed'
                   ) THEN
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'notification outbox requires valid review provenance';
                END IF;
                RETURN NEW;
            END;
            $$
            """
        )
        op.execute(
            """
            CREATE OR REPLACE FUNCTION pilot_validate_evidence_duration()
            RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE
                duration_seconds double precision;
            BEGIN
                duration_seconds := EXTRACT(EPOCH FROM (NEW.end_at - NEW.start_at));
                IF duration_seconds <= 0
                   OR duration_seconds > 10
                   OR (NEW.status = 'ready' AND duration_seconds < 4) THEN
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'evidence duration violates the bounded clip policy';
                END IF;
                RETURN NEW;
            END;
            $$
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_evidence_duration
            BEFORE INSERT OR UPDATE ON evidence
            FOR EACH ROW EXECUTE FUNCTION pilot_validate_evidence_duration()
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_notification_outbox_confirmed_operator
            BEFORE INSERT ON notification_outbox
            FOR EACH ROW EXECUTE FUNCTION pilot_validate_notification_outbox()
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivery_attempts")
    op.drop_table("reviews")
    op.drop_table("notification_outbox")
    op.drop_table("evidence")
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index("ix_observations_camera_source_time")

    op.drop_table("observations")
    with op.batch_alter_table("candidate_events", schema=None) as batch_op:
        batch_op.drop_index("ix_candidate_events_filters")
        batch_op.drop_index("ix_candidate_events_camera_opened")

    op.drop_table("candidate_events")
    with op.batch_alter_table("camera_health_samples", schema=None) as batch_op:
        batch_op.drop_index("ix_camera_health_camera_observed")

    op.drop_table("camera_health_samples")
    op.drop_table("gate_reports")
    with op.batch_alter_table("cameras", schema=None) as batch_op:
        batch_op.drop_index("ix_cameras_site_state")

    op.drop_table("cameras")
    with op.batch_alter_table("audit_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_entries_entity")

    op.drop_table("audit_entries")
    op.drop_table("users")
    op.drop_table("sites")
    op.drop_table("model_artifacts")
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS pilot_reject_audit_mutation()")
        op.execute("DROP FUNCTION IF EXISTS pilot_validate_notification_outbox()")
        op.execute("DROP FUNCTION IF EXISTS pilot_validate_evidence_duration()")
    # ### end Alembic commands ###
